services:
  app:
    image: registrygitlab.ssaver.gob.mx/boletas/api-boletas/app:latest-test
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
    secrets:
      - source: 2025ssaver_crt_complete
        target: /cert/ssaver.gob.mx.crt
      - source: 2025ssaver_key
        target: /cert/ssaver.gob.mx.key
    networks:
      - cae-services

networks:
  cae-services:
    external: true

secrets:
  2025ssaver_key:
    external: true
  2025ssaver_crt_complete:
    external: true
