services:
  api-boletas:
    image: registry.ssaver.gob.mx:5000/boletas-api:latest
    container_name: boletas-api
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - 6888:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
  db:
    image: mariadb:10.7.1
    container_name: boletas-db
    restart: unless-stopped
    ports:
      - 3316:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - boletas_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD_ROOT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  boletas_db: